export enum PropertyTags {
  RENT = 'rent',
  SELL = 'sell',
  FEATURED = 'featured',
  ONSALE = 'onSale',
  NEW = 'new',
  HOT = 'hot',
  POPULAR = 'popular',
  EXCLUSIVE = 'exclusive',
  LUXURY = 'luxury',
  FURNISHED = 'furnished',
  UNFURNISHED = 'unfurnished',
  APARTMENT = 'apartment',
  HOUSE = 'house',
  VILLA = 'villa',
  COMMERCIAL = 'commercial',
  INDUSTRIAL = 'industrial',
  LAND = 'land',
  COTTAGE = 'cottage',
}
